repositories:
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts

releases:
- name: prom
  namespace: monitoring
  createNamespace: true
  chart: prometheus-community/kube-prometheus-stack
  version: 41.5.1
  values:
  - values.yaml