apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kuard
spec:
  endpoints:
  - port: http
    scheme: http
    path: /metrics
    honorLabels: true
    scrapeTimeout: 30s
  namespaceSelector:
    matchNames:
      - kuard
  selector:
    matchLabels:
      app: kuard